// @name Authenticate-ErrorWithoutCode
GET http://localhost:3000/authenticate

###

// @name AuthenticateWithTwitch
GET http://localhost:3000/authenticate/
    ?code=xhmvrf7wvx20je3m5et2zhzeiv0iq7
    &scope=chat:edit+chat:read

###

// @name RefreshAccessTokenByTwitchID
GET http://localhost:3000/refresh-token
    ?twitch_id=115415445
    &refresh_token=asd

###

// @name GetUserById
GET http://localhost:3000/user/
    ?access_token=up780adu2ujctnehlgw7s5e27fzr2l
    &id=115415445