// @name Authenticate-ErrorWithoutCode
GET http://localhost:3000/authenticate

###

// @name AuthenticateWithTwitch
GET http://localhost:3000/authenticate/
    ?code=e1asjwo8ukhzh8t9p5phtknt3fw0tu
    &scope=chat:edit+chat:read

###

// @name RefreshAccessTokenByTwitchID
GET http://localhost:3000/refresh-token
    ?twitch_id=115415445
    &refresh_token=asd

###

// @name initializeBot-pookiepew
GET http://localhost:3000/bot/initialize
    ?login=pookiepew
    &access_token=
    &channel=pookiepew

###

// @name initializeBot-pooksibot
GET http://localhost:3000/bot/initialize
    ?login=pooksibot
    &access_token=
    &channel=pooksibot